#!/bin/bash
for f in ./config.*; do
    rm -f $f
done
if [ -e confdefs.h ]; then
    rm -f confdefs.h
fi
if [ -e src/Makevars ]; then
    rm -f src/Makevars
fi
for f in src/*.o src/*.so; do
    rm -f $f
done
find . -name \*~ | xargs rm -f
exit 0
